-- MySQL Script generated by MySQL Workbench
-- Thu 21 Dec 2017 10:31:24 AM STD
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema user_api
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `user_api` ;

-- -----------------------------------------------------
-- Schema user_api
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `user_api` DEFAULT CHARACTER SET latin1 ;
USE `user_api` ;

-- -----------------------------------------------------
-- Table `user_api`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_api`.`user` ;

CREATE TABLE IF NOT EXISTS `user_api`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `hash` VARCHAR(255) NOT NULL,
  `salt` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
